filebeat.prospectors:
- input_type: log
  paths:
    - /data/*.csv

  # Ignore the first line with column headings
  exclude_lines: ["^Id commande,"]

setup.template:
  enabled: true
  name: 'sales-log'
  pattern: 'sales-log-*'
  overwrite: true
  settings:
    number_of_shards: 1
    number_of_replicas: 1

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  pipeline: "sales-log-pipeline"
  index: "sales-log"
